// This file is a template for app/api/_isd/events/route.ts
// Generated by CLI init command

export async function GET() {
  const { startWatcher, addSSEWriter } = await import('idml/server');
  const CONFIG_PATH = process.env.ISD_UI_CONFIG_PATH!;

  startWatcher(CONFIG_PATH);

  const encoder = new TextEncoder();
  const stream = new ReadableStream({
    start(controller) {
      // Send initial ping to establish connection
      controller.enqueue(encoder.encode(': ping\n\n'));

      // Heartbeat every 25 seconds
      const interval = setInterval(() => {
        try {
          controller.enqueue(encoder.encode(': heartbeat\n\n'));
        } catch {
          clearInterval(interval);
        }
      }, 25_000);

      // Register as SSE client
      const unregister = addSSEWriter(controller as any);

      return () => {
        clearInterval(interval);
        unregister();
      };
    },
  });

  return new Response(stream, {
    headers: {
      'Content-Type': 'text/event-stream',
      'Cache-Control': 'no-cache, no-transform',
      'X-Accel-Buffering': 'no',
      Connection: 'keep-alive',
    },
  });
}

export const dynamic = 'force-dynamic';
export const runtime = 'nodejs';
